// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxxzjalvphmfvpzdtebk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4eHpqYWx2cGhtZnZwemR0ZWJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1ODk0MDEsImV4cCI6MjA2MzE2NTQwMX0.bY5QEBhb0eEQRp48WNEw95mO9FbAM10-P56X3B3rBDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);